# Не проверяем Gemfile.
AllCops:
  Exclude:
    - Gemfile
# Разумно увеличиваем максимальную длину строки.
Metrics/LineLength:
  Max: 120
# Так как задачи искусственные и математические,
# целесообразно увеличить ограничение на максимальное количество строк метода.
Metrics/MethodLength:
  Max: 15
# Так как мы не занимаемся международной разработкой и преследуем образовательные цели,
# для большей наглядности разрешим русские комментарии.
Style/AsciiComments:
  Enabled: false
# Чтобы было меньше "лишних" комментариев, отключим требования к документированию кода
# (но вообще-то требование, конечно, хорошее и правильное).
Style/Documentation:
    Enabled: false
