---
detectors:
  # Отключение комментариев к классу - в данном случае они требуются только для
  # тестового класса, а там они, полагаю, не нужны.
  IrresponsibleModule:
    enabled: false
  NestedIterators:
    max_allowed_nesting: 2
  # Более подробно об этой проверке можно почитать здесь:
  # https://github.com/troessner/reek/blob/v5.4.0/docs/Nil-Check.md
  # Несмотря на то, что следует избегать такого кода, в данном случае для упрощения логики
  # можно игнорировать эту проверку.
  NilCheck:
    enabled: false
  # Для математических операций можно повысить ограничение на максимальное количество операций
  # в методе и сделать его равным максимальному количеству строк в методе, заданному в конфигурации рубокопа.
  TooManyStatements:
    max_statements: 15
  # Избегаем односимвольных имен, но для x и y (так как y = f(x)) сделаем исключение.
  UncommunicativeVariableName:
    accept:
      - x
      - y
  UtilityFunction:
    enabled: false
