# Не проверяем Gemfile.
AllCops:
  Exclude:
    - Gemfile
  NewCops: enable
# Разумно увеличиваем максимальную длину строки.
Layout/LineLength:
  Max: 120
# Для тестов повысим максимально допустимое значение метрики ABC
# https://en.wikipedia.org/wiki/ABC_Software_Metric
Metrics/AbcSize:
  Max: 20
# Так как задачи искусственные и математические,
# целесообразно увеличить ограничение на максимальное количество строк метода.
Metrics/MethodLength:
  Max: 15
# Так как мы не занимаемся международной разработкой и преследуем образовательные цели,
# для большей наглядности разрешим русские комментарии.
Style/AsciiComments:
  Enabled: false
# Чтобы было меньше "лишних" комментариев, отключим требования к документированию кода
# (но вообще-то требование, конечно, хорошее и правильное).
Style/Documentation:
  Enabled: false
